name: E2E Suite

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/e2e.yml"
      - "lib/**"
      - "proto/**"
      - "scripts/**"
      - "skaffold/**"
      - "src/**"
      - "tests/**"
      - "Cargo.lock"
      - "Cargo.toml"
      - "build.rs"
      - "docker-compose.yml"
      - "Makefile"
      - "rust-toolchain"
  pull_request: {}

env:
  VERBOSE: true
  RUST_TEST_THREADS: 1
  TEST_LOG: vector=debug
  RUST_BACKTRACE: full
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  test-e2e-kubernetes:
    name: K8s ${{ matrix.kubernetes_version }} / ${{ matrix.container_runtime }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minikube_version:
          - "v1.11.0" # https://github.com/kubernetes/minikube/issues/8799
        kubernetes_version:
          - "v1.18.6"
          # TODO: https://github.com/timberio/vector/issues/3338
          #- "v1.17.9"
          #- "v1.16.12" # v1.16.13 is broken, see https://github.com/kubernetes/minikube/issues/8840
          #- "v1.15.12"
          - "v1.14.10"
        container_runtime:
          - docker
          - containerd
          - crio
      fail-fast: false
    steps:
      - name: Setup Minikube
        run: |
          set -xeuo pipefail

          curl -Lo kubectl \
            'https://storage.googleapis.com/kubernetes-release/release/${{ matrix.kubernetes_version }}/bin/linux/amd64/kubectl'
          sudo install kubectl /usr/local/bin/ && rm kubectl

          curl -Lo minikube \
            'https://storage.googleapis.com/minikube/releases/${{ matrix.minikube_version }}/minikube-linux-amd64'
          sudo install minikube /usr/local/bin/ && rm minikube

          minikube config set profile minikube
          minikube config set vm-driver docker
          minikube config set kubernetes-version '${{ matrix.kubernetes_version }}'
          minikube config set container-runtime '${{ matrix.container_runtime }}'
          # Start minikube, try again once if fails and print logs if the second
          # attempt fails too.
          minikube start || minikube delete && minikube start || minikube logs
          kubectl cluster-info
      - name: Checkout
        uses: actions/checkout@v1
      - run: USE_CONTAINER=none make slim-builds
      - run: make test-e2e-kubernetes
        env:
          USE_MINIKUBE_CACHE: "true"
          PACKAGE_DEB_USE_CONTAINER: docker
